import LoadableComponent from './../Loadable/index';

export const userRouter: any = [
  {
    path: '/user',
    name: 'user',
    title: 'User',
    component: LoadableComponent(() => import('../../components/Layout/UserLayout')),
    isLayout: true,
    showInMenu: false,
  },
  {
    path: '/user/login',
    name: 'login',
    title: 'LogIn',
    component: LoadableComponent(() => import('../../scenes/Login')),
    showInMenu: false,
  },
  {
    path: '/user/adminlogin',
    name: 'login',
    title: 'AdminLogIn',
    component: LoadableComponent(() => import('../../scenes/AdminLogin')),
    showInMenu: false,
  },
];

export const appRouters: any = [
  {
    path: '/',
    exact: true,
    name: 'home',
    permission: '',
    title: 'Home',
    icon: 'home',
    component: LoadableComponent(() => import('../../components/Layout/AppLayout')),
    isLayout: true,
    showInMenu: false,
  },
  // {
  //   path: '/dashboard',
  //   name: 'dashboard',
  //   permission: 'Pages.Admin',
  //   title: 'Dashboard',
  //   icon: 'home',
  //   showInMenu: true,
  //   component: LoadableComponent(() => import('../../scenes/Dashboard')),
  // },
  {
    path: '/country_master',
    name: 'country_master',
    permission: 'Pages.Admin',
    title: 'Country Master',
    icon: '',
    showInMenu: true,
    innerMenu: true,
    component: LoadableComponent(() => import('../../scenes/Masters/CountryMaster')),
  },
  {
    path: '/department_master',
    name: 'department_master',
    permission: 'Pages.Admin',
    title: 'Department Master',
    icon: '',
    showInMenu: true,
    innerMenu: true,
    component: LoadableComponent(() => import('../../scenes/Masters/DepartmentMaster')),
  },
  {
    path: '/designation_master',
    name: 'designation_master',
    permission: 'Pages.Admin',
    title: 'Designation Master',
    icon: '',
    showInMenu: true,
    innerMenu: true,
    component: LoadableComponent(() => import('../../scenes/Masters/DesignationMaster')),
  },
  {
    path: '/public_holiday_master',
    name: 'public_holiday_master',
    permission: 'Pages.Admin',
    title: 'Public Holiday Master',
    icon: '',
    showInMenu: true,
    innerMenu: true,
    component: LoadableComponent(() => import('../../scenes/Masters/PublicHolidayMaster')),
  },
  {
    path: '/leave_type_master',
    name: 'leave_type_master',
    permission: 'Pages.Admin',
    title: 'Leave Type Master',
    icon: '',
    showInMenu: true,
    innerMenu: true,
    component: LoadableComponent(() => import('../../scenes/Masters/LeaveTypeMaster')),
  },
  {
    path: '/leave_entitlement_master',
    name: 'leave_entitlement_master',
    permission: 'Pages.Admin',
    title: 'Leave Entitlement Master',
    icon: '',
    showInMenu: true,
    innerMenu: true,
    component: LoadableComponent(() => import('../../scenes/Masters/LeaveEntitlementMaster')),
  },

  {
    path: '/roles',
    permission: 'Pages.Admin',
    title: 'Role Master',
    name: 'role',
    // icon: 'tags',
    showInMenu: true,
    innerMenu: true,
    component: LoadableComponent(() => import('../../scenes/Roles')),
  },
  {
    path: '/users',
    permission: 'Pages.Admin',
    title: 'Manage Roles',
    name: 'user',
    icon: 'user',
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Users')),
  },
  {
    path: '/tenants',
    permission: 'Pages.Tenants',
    title: 'Tenants',
    name: 'tenant',
    icon: 'appstore',
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Tenants')),
  },
  {
    path: '/employee_management',
    name: 'employee_management',
    permission: 'Pages.Admin',
    title: 'Employee Management',
    icon: 'user',
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/EmpManagement/EmployeeManagement')),
  },
  // {
  //   path: '/employee_profile',
  //   name: 'employee_profile',
  //   permission: '',
  //   title: 'My Profile',
  //   icon: 'project',
  //   showInMenu: true,
  //   component: LoadableComponent(() => import('../../scenes/EmployeeProfile/EmployeeProfile')),
  // },
  {
    path: '/my_profile',
    name: 'my_profile',
    permission: '',
    title: 'My Profile',
    icon: 'project',
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/MyProfile/MyProfile')),
  },
  {
    path: '/employee_details',
    permission: '',
    title: 'Employee Details',
    name: 'employee_details',
    icon: 'info-circle',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/EmpManagement/EmployeeDetails')),
  },
  {
    path: '/create_leave_request',
    name: 'create_leave_request',
    permission: '',
    title: 'Request Leave',
    icon: 'bar-chart',
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/RequestLeave/RequestLeave')),
  },
  {
    path: '/leave_approval',
    name: 'leave_approval',
    permission: 'Pages.Approver',
    title: 'Leave Approval',
    icon: 'form',
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/LeaveApproval/LeaveApproval')),
  },
  {
    path: '/leave_report',
    name: 'leave_report',
    permission: 'Pages.Approver',
    title: 'Leave Report',
    icon: 'history',
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/LeaveReport/LeaveReport')),
  },
  {
    path: '/leave_report_details',
    name: 'leave_report_details',
    permission: '',
    title: 'Leave Report Details',
    icon: 'history',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/LeaveReport/LeaveReportDetails')),
  },
  {
    path: '/leave_log',
    name: 'leave_log',
    permission: '',
    title: 'Leave Log',
    icon: 'history',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/LeaveLog/LeaveLog')),
  },
  {
    path: '/logout',
    permission: '',
    title: 'Logout',
    name: 'logout',
    icon: 'info-circle',
    showInMenu: false,
    component: LoadableComponent(() => import('../../components/Logout')),
  },
  {
    path: '/exception?:type',
    permission: '',
    title: 'exception',
    name: 'exception',
    icon: 'info-circle',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Exception')),
  },
  {
    path: '/exception?:type',
    permission: '',
    title: 'exception',
    name: 'exception',
    icon: 'info-circle',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Exception')),
  },
  {
    path: '/leave_details',
    permission: '',
    title: 'exception',
    name: 'exception',
    icon: 'info-circle',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/EmployeeProfile/LeaveDetails')),
  },
  {
    path: '/amend_and_reapply',
    permission: '',
    title: 'exception',
    name: 'exception',
    icon: 'info-circle',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/EmployeeProfile/ReapplyLeave')),
  },
  {
    path: '/initiate_carry_forward',
    name: 'initiate_carry_forward',
    permission: 'Pages.Admin',
    title: 'Initiate Carry Forward',
    icon: 'warning',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/InitiateCarryForward/InitiateCarryForward')),
  },
];

export const routers = [...userRouter, ...appRouters];
